name: ani_search
description: asdasdas

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.3"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  http: ^0.13.4
  # Utils
  provider: ^6.0.3
  get:
  sliver_tools: ^0.2.7
  flutter_svg: ^1.1.1+1
  # get_it: ^7.2.0
  lazy_load_scrollview: 1.3.0
  percent_indicator: ^4.0.1
  flutter_layout_grid: ^2.0.1
  boxy: ^2.0.6+1

  # Monet
  dynamic_color: ^1.1.2
  expandable: ^5.0.1

  # Google
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6

  # Cache
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.1

  # Icons
  cupertino_icons: ^1.0.2

  # Localizations
  # klocalizations_flutter: ^0.0.7
  localization: ^2.1.0

  # Api
  graphql: ^5.1.1
  # dio: ^4.0.6

  # Storage
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0

  # Html
  flutter_widget_from_html_core: ^0.8.5+3
  # flutter_html: ^2.2.1

  # onload ...
  pull_to_refresh: ^2.0.0
  # refresh_loadmore: ^2.0.5

  # animations
  flutter_staggered_animations: ^1.0.0
  auto_animated: ^3.0.1

  # id
  uuid: 3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator: ^1.1.3

  flutter_lints: ^2.0.0
  msix: ^2.8.18

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - i18n/
    - assets/img/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
